.TH "econf_ext_value" 3 "Wed Mar 24 2021" "Version 0.4.0" "libeconf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
econf_ext_value\fC#include <libeconf_ext\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char ** \fBvalues\fP"
.br
.ti -1c
.RI "char * \fBfile\fP"
.br
.ti -1c
.RI "uint64_t \fBline_number\fP"
.br
.ti -1c
.RI "char * \fBcomment_before_key\fP"
.br
.ti -1c
.RI "char * \fBcomment_after_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file libeconf_ext\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char** econf_ext_value::values"

.PP
Definition at line 38 of file libeconf_ext\&.h\&.
.SS "char* econf_ext_value::file"

.PP
Definition at line 39 of file libeconf_ext\&.h\&.
.SS "uint64_t econf_ext_value::line_number"

.PP
Definition at line 40 of file libeconf_ext\&.h\&.
.SS "char* econf_ext_value::comment_before_key"

.PP
Definition at line 41 of file libeconf_ext\&.h\&.
.SS "char* econf_ext_value::comment_after_value"

.PP
Definition at line 42 of file libeconf_ext\&.h\&.
