'\" t
.\"     Title: ECONF_DELIMITER_TAG
.\"    Author: libeconf developers
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 2025-12-04
.\"    Manual: libeconf Library Functions
.\"    Source: libeconf
.\"  Language: English
.\"
.TH "ECONF_DELIMITER_TAG" "3" "2025\-12\-04" "libeconf" "libeconf Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH "NAME"
econf_delimiter_tag \- get the key\-value delimiter character from a configuration file structure

.SH "SYNOPSIS"

.sp
.ft B
.nf
#include <libeconf\&.h>
.fi
.ft
.sp

.BI "char econf_delimiter_tag(econf_file\ *" "key_file" ");"

.SH "DESCRIPTION"

.PP
The \fBeconf_delimiter_tag\fR() function retrieves the character used as the delimiter between keys and values in the configuration file represented by the structure pointed to by \fIkey_file\fR\&.

.PP
For standard INI\-style files, this delimiter is typically the equals sign (=)\&. The delimiter can be set manually during file creation or parsing (e\&.g\&., via
\fBeconf_set_delimiter_tag\fR())\&. This function allows retrieving the currently configured delimiter\&.

.SH "RETURN VALUE"

.PP
On success, \fBeconf_delimiter_tag\fR() returns the delimiter character (\fBchar\fR)\&.

.SH "ERRORS"

.PP
This function does not return an \fBeconf_err\fR code directly\&.

.SH "SEE ALSO"

.PP
\fBeconf_comment_tag\fR(3),
\fBeconf_set_delimiter_tag\fR(3),
\fBeconf_readConfig\fR(3),
\fBeconf_errString\fR(3)

.RE
