'\" t
.\"     Title: ECONF_SET_DELIMITER_TAG
.\"    Author: libeconf Developers
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 2025-12-04
.\"    Manual: libeconf Manual
.\"    Source: libeconf
.\"  Language: English
.\"
.TH "ECONF_SET_DELIMITER_" "3" "2025\-12\-04" "libeconf" "libeconf Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH "NAME"
econf_set_delimiter_tag \- set the key\-value delimiter character used during file parsing

.SH "SYNOPSIS"

.sp
.ft B
.nf
#include <libeconf\&.h>
.fi
.ft
.sp

.BI "void econf_set_delimiter_tag(const\ char\ " "delimiter" ");"

.SH "DESCRIPTION"

.PP
The \fBeconf_set_delimiter_tag\fR() function sets the character or string used to separate a configuration \fIkey\fR from its corresponding \fIvalue\fR
when reading/writing configuration files\&.

.PP
The \fIdelimiter\fR argument specifies the new delimiter tag\&. I

.SH "RETURN VALUE"

.PP
none

.SH "SEE ALSO"

.PP
\fBlibeconf\fR(3),
\fBeconf_get_delimiter_tag\fR(3),
\fBeconf_set_comment_tag\fR(3).

.RE
